import { getDiagramImageAsset } from "@/lib/instructor/diagrams/image-asset";
import type { TeachingDiagram } from "@/lib/instructor/diagrams/types";

export const TEACHING_DIAGRAMS: TeachingDiagram[] = [
  {
    slug: "left-emerge",
    title: "Emerging left",
    description:
      "Side-road approach when turning left onto a priority road. Use MSPSL, position left, and emerge only when the main road is clear.",
    category: "junctions",
    teachingTimeMinutes: 8,
    difficulty: "beginner",
    teachingPoints: [
      "Mirrors, then signal left in good time as you approach the give way lines.",
      "Position close to the left kerb so following traffic can pass if the junction is open.",
      "Peep and creep: observations into the main road, including the blind spot on your right.",
      "Emerge smoothly without forcing oncoming traffic to change speed or direction.",
    ],
    commonMistakes: [
      "Emerging without effective observations into the main road.",
      "Cutting the corner and straying onto the wrong side of the side road.",
      "Hesitating in the mouth of the junction when a safe gap is clearly available.",
    ],
    relatedSlugs: ["right-emerge", "left-turn", "crossroad"],
    keywords: ["emerging", "left", "give way", "mspsl", "t junction", "priority road"],
    image: getDiagramImageAsset("left-emerge"),
  },
  {
    slug: "right-emerge",
    title: "Emerging right",
    description:
      "Side-road approach when turning right onto a priority road. Cross oncoming traffic only when a safe gap is available.",
    category: "junctions",
    teachingTimeMinutes: 10,
    difficulty: "intermediate",
    teachingPoints: [
      "Mirrors and right signal in good time; position just left of centre if the road is wide enough.",
      "At the give way lines, take observations left, right, and left again.",
      "Wait for a safe gap in both directions; do not assume oncoming traffic will slow for you.",
      "Steer positively into the correct lane without cutting the corner.",
    ],
    commonMistakes: [
      "Positioning too far right and blocking the view of oncoming traffic.",
      "Emerging when oncoming traffic is too close or too fast.",
      "Failing to check the nearside mirror and blind spot before steering out.",
    ],
    relatedSlugs: ["left-emerge", "right-turn", "crossroad"],
    keywords: ["emerging", "right", "give way", "observations", "priority"],
    image: getDiagramImageAsset("right-emerge"),
  },
  {
    slug: "left-turn",
    title: "Turning left",
    description:
      "Approach a left turn on the main road using MSPSL, keep left, and maintain observations through the turn.",
    category: "junctions",
    teachingTimeMinutes: 7,
    difficulty: "beginner",
    teachingPoints: [
      "Mirror and left signal before the turn; reduce speed on approach.",
      "Keep to the left and follow the kerb line through the bend.",
      "Check for pedestrians and cyclists on the nearside before and during the turn.",
      "Do not swing wide into the path of following or oncoming traffic.",
    ],
    commonMistakes: [
      "Signalling too late or not at all.",
      "Cutting the corner across the path of oncoming traffic.",
      "Drifting wide after the turn into the wrong lane.",
    ],
    relatedSlugs: ["right-turn", "left-emerge", "crossroads-scenarios"],
    keywords: ["left turn", "position", "signal", "mspsl", "junction"],
    image: getDiagramImageAsset("left-turn"),
  },
  {
    slug: "right-turn",
    title: "Turning right",
    description:
      "Approach a right turn with correct position, give way to oncoming traffic, and complete the turn in the correct lane.",
    category: "junctions",
    teachingTimeMinutes: 9,
    difficulty: "intermediate",
    teachingPoints: [
      "Mirror and right signal; position just left of centre line where the road allows.",
      "Give way to oncoming traffic and pedestrians crossing the road you are entering.",
      "Keep the wheels straight while waiting at the junction.",
      "Steer into the correct lane without cutting the corner.",
    ],
    commonMistakes: [
      "Positioning too far left and blocking following traffic unnecessarily.",
      "Turning when oncoming traffic is too close.",
      "Cutting the corner into the wrong side of the new road.",
    ],
    relatedSlugs: ["left-turn", "right-emerge", "crossroads-scenarios"],
    keywords: ["right turn", "give way", "position", "oncoming", "signal"],
    image: getDiagramImageAsset("right-turn"),
  },
  {
    slug: "crossroad",
    title: "Crossroads",
    description:
      "Identify priority, use give way lines correctly, and manage observations at a UK crossroads.",
    category: "junctions",
    teachingTimeMinutes: 10,
    difficulty: "intermediate",
    teachingPoints: [
      "Read road markings and layout early to confirm which road has priority.",
      "At give way lines, stop if required and observe in all relevant directions.",
      "Keep wheels straight while waiting so the car cannot roll into the junction.",
      "Cross or turn decisively once safe, without blocking the junction.",
    ],
    commonMistakes: [
      "Assuming priority without checking cross-traffic.",
      "Blocking the junction while hesitating.",
      "Poor lane discipline when crossing a wide junction.",
    ],
    relatedSlugs: ["crossroads-scenarios", "left-emerge", "right-emerge"],
    keywords: ["crossroads", "crossroad", "priority", "give way", "observations"],
    image: getDiagramImageAsset("crossroad"),
  },
  {
    slug: "crossroads-scenarios",
    title: "Crossroads scenarios",
    description:
      "Common crossroad layouts and priorities. Plan each movement separately and read signs and markings early.",
    category: "junctions",
    teachingTimeMinutes: 12,
    difficulty: "intermediate",
    teachingPoints: [
      "Identify whether the junction is open, closed, marked, or unmarked.",
      "Treat each approach as a separate decision: who has priority and where you will steer.",
      "Use appropriate speed so you can stop at give way lines if needed.",
      "Signal clearly so other road users understand your intention.",
    ],
    commonMistakes: [
      "Treating different crossroad types the same way without reading the layout.",
      "Failing to check for traffic from the right at unmarked junctions.",
      "Late lane changes before the junction.",
    ],
    relatedSlugs: ["crossroad", "left-turn", "right-turn", "staggered-junction"],
    keywords: ["crossroads", "scenarios", "priority", "layout", "junction"],
    image: getDiagramImageAsset("crossroads-scenarios"),
  },
  {
    slug: "meeting-traffic",
    title: "Meeting traffic",
    description:
      "Assess gaps, reduce speed, and hold a safe position when meeting oncoming traffic on a narrow UK road.",
    category: "meeting-traffic",
    teachingTimeMinutes: 8,
    difficulty: "beginner",
    teachingPoints: [
      "Read the road ahead early for oncoming vehicles and passing places.",
      "Reduce speed and be prepared to stop in a safe holding position.",
      "Give way where the Highway Code and local layout require it.",
      "Pass with adequate clearance without mounting the kerb.",
    ],
    commonMistakes: [
      "Continuing at speed when a meeting conflict is obvious.",
      "Stopping opposite a passing place instead of using it.",
      "Poor clearance past parked obstructions or pedestrians.",
    ],
    relatedSlugs: ["left-turn", "crossroad"],
    keywords: ["meeting traffic", "narrow road", "passing place", "give way"],
    image: getDiagramImageAsset("meeting-traffic"),
  },
  {
    slug: "roundabout",
    title: "Roundabout",
    description:
      "Approach at an appropriate speed, give way to traffic from the right, and use signals correctly for your exit.",
    category: "roundabouts",
    teachingTimeMinutes: 10,
    difficulty: "intermediate",
    teachingPoints: [
      "Reduce speed on approach; check mirrors and signals early.",
      "Give way to traffic already circulating from the right.",
      "Choose the correct lane for your exit and maintain lane discipline.",
      "Signal left after passing the exit before the one you intend to take.",
    ],
    commonMistakes: [
      "Entering without yielding to traffic from the right.",
      "Swerving lanes at the last moment.",
      "Signalling too early or forgetting to signal on exit.",
    ],
    relatedSlugs: ["left-turn", "right-turn", "independent-driving-signs-4"],
    keywords: ["roundabout", "give way", "signal", "lanes", "exit"],
    image: getDiagramImageAsset("roundabout"),
  },
  {
    slug: "staggered-junction",
    title: "Staggered junction",
    description:
      "Two offset side roads meeting a main road. Treat each give way separately and plan your path through the stagger.",
    category: "junctions",
    teachingTimeMinutes: 10,
    difficulty: "intermediate",
    teachingPoints: [
      "Read the layout early: side roads are offset, not directly opposite.",
      "Deal with the first give way before committing to the staggered section.",
      "Keep scanning for traffic from the main road and the opposite side road.",
      "Maintain steady steering through the offset without swinging wide.",
    ],
    commonMistakes: [
      "Treating the junction as one movement instead of two separate decisions.",
      "Failing to check the second give way after crossing the first.",
      "Swinging wide into the path of main-road traffic.",
    ],
    relatedSlugs: ["staggered-junction-1", "crossroads-scenarios", "crossroad"],
    keywords: ["staggered", "junction", "offset", "give way", "priority"],
    image: getDiagramImageAsset("staggered-junction"),
  },
  {
    slug: "staggered-junction-1",
    title: "Staggered junction: scenario",
    description:
      "A worked staggered junction layout. Plan each leg, confirm priority, and keep progress smooth without blocking the main road.",
    category: "junctions",
    teachingTimeMinutes: 10,
    difficulty: "intermediate",
    teachingPoints: [
      "Identify which side road you are using and where the second give way sits.",
      "Use appropriate speed so you can stop again if the stagger opens onto busy traffic.",
      "Signal in good time so other road users understand your route.",
      "Keep wheels straight while waiting at each give way line.",
    ],
    commonMistakes: [
      "Assuming priority carries through the whole stagger without re-checking.",
      "Cutting corners across the mouth of the junction.",
      "Hesitating in the stagger and blocking following traffic.",
    ],
    relatedSlugs: ["staggered-junction", "crossroads-scenarios", "left-emerge"],
    keywords: ["staggered", "scenario", "junction", "give way"],
    image: getDiagramImageAsset("staggered-junction-1"),
  },
  {
    slug: "independent-driving-signs-1",
    title: "Independent drive: direction signs (1)",
    description:
      "Follow UK direction signs during the independent drive. Read signs early and move into the correct lane in good time.",
    category: "independent-driving",
    teachingTimeMinutes: 8,
    difficulty: "intermediate",
    teachingPoints: [
      "Read direction signs well before the junction or roundabout.",
      "Move into the correct lane early; avoid last-second lane changes.",
      "Combine sign information with road markings and layout.",
      "If unsure, continue safely and recover on the next instruction.",
    ],
    commonMistakes: [
      "Swerving across lanes after spotting a sign too late.",
      "Stopping in a live lane to read a sign.",
      "Missing the next sign while fixating on the first.",
    ],
    relatedSlugs: ["independent-driving-signs-2", "independent-driving-signs-3", "roundabout"],
    keywords: ["independent driving", "signs", "direction", "lane discipline"],
    image: getDiagramImageAsset("independent-driving-signs-1"),
  },
  {
    slug: "independent-driving-signs-2",
    title: "Independent drive: direction signs (2)",
    description:
      "Another common UK sign sequence for independent driving. Plan lane position and signalling before the decision point.",
    category: "independent-driving",
    teachingTimeMinutes: 8,
    difficulty: "intermediate",
    teachingPoints: [
      "Use MSPSL when the route requires a turn or lane change.",
      "Check mirrors before changing position for the signed route.",
      "Keep appropriate speed so you can still read the next sign.",
      "Do not block traffic while hesitating at a junction.",
    ],
    commonMistakes: [
      "Late signalling after the decision point has passed.",
      "Drifting into the wrong lane under pressure.",
      "Ignoring supplementary arrow signs on the road surface.",
    ],
    relatedSlugs: ["independent-driving-signs-1", "independent-driving-signs-4", "left-turn"],
    keywords: ["independent driving", "signs", "mspsl", "route"],
    image: getDiagramImageAsset("independent-driving-signs-2"),
  },
  {
    slug: "independent-driving-signs-3",
    title: "Independent drive: direction signs (3)",
    description:
      "Compact sign layout for cab teaching. Emphasise early reading and calm lane discipline on UK roads.",
    category: "independent-driving",
    teachingTimeMinutes: 7,
    difficulty: "beginner",
    teachingPoints: [
      "Pick out the destination or symbol that matches your instructed route.",
      "Position for the movement shown, not the movement you hope to make later.",
      "Scan for pedestrians and cyclists when signs direct you toward urban areas.",
      "Maintain progress appropriate to the road without rushing the decision.",
    ],
    commonMistakes: [
      "Following another vehicle instead of the signed route.",
      "Misreading similar place names on duplicate-style signs.",
      "Braking abruptly after passing the correct turn.",
    ],
    relatedSlugs: ["independent-driving-signs-1", "independent-driving-signs-4", "crossroad"],
    keywords: ["independent driving", "signs", "route", "observations"],
    image: getDiagramImageAsset("independent-driving-signs-3"),
  },
  {
    slug: "independent-driving-signs-4",
    title: "Independent drive: direction signs (4)",
    description:
      "Multi-option sign approach for independent driving practice. Compare choices early and commit smoothly.",
    category: "independent-driving",
    teachingTimeMinutes: 9,
    difficulty: "intermediate",
    teachingPoints: [
      "Compare exit or direction options before you reach the decision point.",
      "Signal only when it benefits other road users and matches your lane.",
      "On roundabouts, count exits and match the sign to the correct lane.",
      "If you miss a turn, continue safely; the route can be recovered.",
    ],
    commonMistakes: [
      "Changing lanes on a roundabout after entering in the wrong lane.",
      "Signalling too early and misleading other drivers.",
      "Stopping illegally to reverse after a missed sign.",
    ],
    relatedSlugs: ["independent-driving-signs-2", "independent-driving-signs-3", "roundabout"],
    keywords: ["independent driving", "signs", "roundabout", "exit"],
    image: getDiagramImageAsset("independent-driving-signs-4"),
  },
];

export const TEACHING_DIAGRAMS_BY_SLUG = Object.fromEntries(
  TEACHING_DIAGRAMS.map((diagram) => [diagram.slug, diagram]),
) as Record<string, TeachingDiagram>;
